version: '3.8'

services:
  backend:
    build: ./posterPlot-Backend
    ports:
      - "8080:8080"
    depends_on:
      - flask
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/posterplot
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=user123

  flask:
    build: ./ 
    ports:
      - "5000:5000"

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: posterplot
      MYSQL_ROOT_PASSWORD: user123
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
