version: '3.8'

services:
  flask:
    build: ./
    ports:
      - "5000:5000"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/ping"]
      interval: 15s
      timeout: 5s
      retries: 10

  backend:
    build: ./posterPlot-Backend
    ports:
      - "8080:8080"
    depends_on:
      - flask
      - db
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/posterplot
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=user123
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: posterplot
      MYSQL_ROOT_PASSWORD: user123
    volumes:
      - db-data:/var/lib/mysql
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      
volumes:
  db-data:

